const $ = (id) => document.getElementById(id);
const WORKER_URL = 'https://pv-capture-ai.mahipal-office21.workers.dev';
const SESSION_KEY = 'prs-assetverify-session-v6';
const STICKY_PREFIX = 'prs-assetverify-sticky-v6-';
const CONDITIONS = ['Good','Fair','Poor','Damaged','Under Repair'];
const STATUSES = ['Found','Not Found','Pending'];
const NOT_FOUND_REASONS = ['','Missing','Disposed','Transferred','Stolen','Under Maintenance'];
const R2_FREE_BYTES = 10 * 1024 * 1024 * 1024;

let session = null;
let companies = [];
let records = [];
let users = [];
let selectedCompany = null;
let pendingPhoto = null;
let editingRecord = null;
let editingUser = null;
let aiSeq = 0;
let activeStatus = 'ALL';

function toast(message, ms=2600){const e=$('toast');e.textContent=message;e.classList.remove('hidden');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.add('hidden'),ms)}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function pad(n){return String(n).padStart(2,'0')}
function fmtDate(d){d=new Date(d);return `${pad(d.getDate())}/${pad(d.getMonth()+1)}/${d.getFullYear()}`}
function fmtTime(d){d=new Date(d);return `${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`}
function isoDateInput(d){const x=new Date(d);return `${x.getFullYear()}-${pad(x.getMonth()+1)}-${pad(x.getDate())}`}
function uid(){return crypto.randomUUID?.() || `${Date.now()}-${Math.random().toString(36).slice(2)}`}
function bytesLabel(n){if(n<1024*1024)return `${(n/1024).toFixed(1)} KB`;if(n<1024*1024*1024)return `${(n/1024/1024).toFixed(1)} MB`;return `${(n/1024/1024/1024).toFixed(2)} GB`}
function isAdmin(){return session?.member?.role==='ADMIN'}
function authHeaders(body=false){const h={};if(body)h['Content-Type']='application/json';if(session?.token)h.Authorization=`Bearer ${session.token}`;return h}
async function api(path, options={}){const opts={...options,headers:{...authHeaders(!!options.body),...(options.headers||{})}};const res=await fetch(`${WORKER_URL}${path}`,opts);if(res.status===401&&session){clearSession();showWelcome();toast('Company session expired. Please login again.')}return res}
async function apiJson(path,options={}){const r=await api(path,options);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Request failed (${r.status})`);return d}
function saveSession(){localStorage.setItem(SESSION_KEY,JSON.stringify(session))}
function clearSession(){session=null;localStorage.removeItem(SESSION_KEY)}
function loadSession(){try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch{return null}}

const allViews=['welcomeView','createCompanyView','existingCompanyView','verifyView','searchView','usersView','usageView','editCompanyView'];
function showView(id){allViews.forEach(v=>$(v).classList.toggle('hidden',v!==id));closeDrawer()}
function showWelcome(){showView('welcomeView');$('menuBtn').classList.add('hidden');$('logoutBtn').classList.add('hidden');$('syncBadge').classList.add('hidden');$('companySubtitle').textContent=''}
function openDrawer(){$('drawer').classList.remove('hidden');$('drawerBackdrop').classList.remove('hidden')}
function closeDrawer(){$('drawer').classList.add('hidden');$('drawerBackdrop').classList.add('hidden')}
function updateShell(){if(!session)return;$('menuBtn').classList.remove('hidden');$('logoutBtn').classList.remove('hidden');$('syncBadge').classList.remove('hidden');$('syncBadge').textContent='Cloud';$('companySubtitle').textContent=session.company.name;$('drawerCompany').textContent=session.company.name;$('drawerUser').textContent=session.member?`${session.member.name} · ${session.member.role==='ADMIN'?'Admin':'Verifier'}`:'Team member not selected';document.querySelectorAll('[data-admin-only]').forEach(e=>e.classList.toggle('hidden',!isAdmin()))}

// ---------- Welcome / company creation ----------
function createMemberRow(data={},locked=false){const wrap=document.createElement('div');wrap.className='member-row member-row-v6';wrap.innerHTML=`
  <label>Full Name *<input class="cm-name" value="${escapeHtml(data.name||'')}" placeholder="Member name"></label>
  <label>Role / Rights *<select class="cm-role"><option value="ADMIN" ${data.role==='ADMIN'?'selected':''}>Admin</option><option value="VERIFIER" ${data.role==='VERIFIER'?'selected':''}>Verifier</option></select></label>
  <button class="remove-member" type="button" ${locked?'disabled':''}>✕</button>`;
  wrap.querySelector('.remove-member').onclick=()=>wrap.remove();return wrap
}
function resetCreateCompany(){$('newCompanyName').value='';$('newCompanyStartDate').value=isoDateInput(new Date());$('newCompanyUsername').value='';$('newCompanyPassword').value='';$('createMembers').innerHTML='';$('createMembers').appendChild(createMemberRow({role:'ADMIN'},true));$('createMembers').appendChild(createMemberRow({role:'VERIFIER'}))}
function collectCreateMembers(){return [...$('createMembers').querySelectorAll('.member-row')].map(r=>({name:r.querySelector('.cm-name').value.trim(),role:r.querySelector('.cm-role').value}))}
$('openCreateCompanyBtn').onclick=()=>{resetCreateCompany();showView('createCompanyView')};
$('openExistingCompanyBtn').onclick=async()=>{showView('existingCompanyView');await loadCompanies()};
document.querySelectorAll('[data-back-welcome]').forEach(b=>b.onclick=showWelcome);
$('addCreateMemberBtn').onclick=()=>$('createMembers').appendChild(createMemberRow({role:'VERIFIER'}));
$('createCompanyBtn').onclick=async()=>{const name=$('newCompanyName').value.trim(),startDate=$('newCompanyStartDate').value,username=$('newCompanyUsername').value.trim(),password=$('newCompanyPassword').value,members=collectCreateMembers();if(!name||!startDate||!username||!password){toast('Complete company name, start date, company username and company password.');return}if(password.length<6){toast('Company password must be at least 6 characters.');return}if(members.length<1||members.some(m=>!m.name)){toast('Enter a name for every team member.');return}if(!members.some(m=>m.role==='ADMIN')){toast('At least one Admin is required.');return}try{const d=await apiJson('/public/companies',{method:'POST',body:JSON.stringify({name,startDate,username,password,members})});session=d.session;saveSession();await enterCompany()}catch(e){toast(e.message,4200)}};

async function loadCompanies(){try{const d=await apiJson('/public/companies');companies=d.companies||[];$('companyList').innerHTML=companies.map(c=>`<div class="company-row"><button data-company="${c.id}"><strong>${escapeHtml(c.name)}</strong><span>${escapeHtml(c.code)}</span></button><span class="company-users">${c.memberCount} member${c.memberCount===1?'':'s'}</span><span class="company-start">Start: ${escapeHtml(c.startDate)}</span><span class="status-active">Active</span></div>`).join('');$('noCompanies').classList.toggle('hidden',companies.length>0);document.querySelectorAll('[data-company]').forEach(b=>b.onclick=()=>openLogin(b.dataset.company))}catch(e){toast(e.message)}}
function openLogin(id){selectedCompany=companies.find(c=>String(c.id)===String(id));if(!selectedCompany)return;$('loginCompanyName').textContent=selectedCompany.name;$('loginUsername').value='';$('loginPassword').value='';$('loginModal').classList.remove('hidden');setTimeout(()=>$('loginUsername').focus(),120)}
$('loginBtn').onclick=async()=>{try{const d=await apiJson('/auth/login',{method:'POST',body:JSON.stringify({companyId:selectedCompany.id,username:$('loginUsername').value.trim(),password:$('loginPassword').value})});session=d.session;saveSession();$('loginModal').classList.add('hidden');await enterCompany()}catch(e){toast(e.message,4000)}};
$('forgotPasswordBtn').onclick=()=>{$('loginModal').classList.add('hidden');$('forgotStep1').classList.remove('hidden');$('forgotStep2').classList.add('hidden');$('forgotUsername').value=$('loginUsername').value.trim();$('resetCode').value='';$('newPassword').value='';$('forgotModal').classList.remove('hidden')};
$('sendResetBtn').onclick=async()=>{try{const d=await apiJson('/auth/forgot',{method:'POST',body:JSON.stringify({companyId:selectedCompany.id,username:$('forgotUsername').value.trim()})});$('forgotStep1').classList.add('hidden');$('forgotStep2').classList.remove('hidden');toast(d.emailConfigured?'Reset code sent to recovery email.':'Reset request created, but email delivery is not configured yet.',4500)}catch(e){toast(e.message,4200)}};
$('resetPasswordBtn').onclick=async()=>{try{await apiJson('/auth/reset',{method:'POST',body:JSON.stringify({companyId:selectedCompany.id,username:$('forgotUsername').value.trim(),code:$('resetCode').value.trim(),newPassword:$('newPassword').value})});$('forgotModal').classList.add('hidden');toast('Company password changed. Login with the new password.');openLogin(selectedCompany.id)}catch(e){toast(e.message,4200)}};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).classList.add('hidden'));

async function restoreSession(){session=loadSession();if(!session){showWelcome();return}try{const d=await apiJson('/auth/me');session=d.session;saveSession();await enterCompany()}catch{clearSession();showWelcome()}}
async function enterCompany(){updateShell();loadSticky();await refreshUsers();if(!session.member){showMemberSelector();return}await refreshRecords();showView('verifyView')}
function showMemberSelector(){if(!session)return;$('memberSelectList').innerHTML=users.filter(u=>u.active!==0).map(u=>`<button class="member-select-btn" data-member-select="${u.id}"><span>${escapeHtml(u.name)}</span><small>${u.role==='ADMIN'?'Admin':'Verifier'}</small></button>`).join('');$('memberSelectModal').classList.remove('hidden');document.querySelectorAll('[data-member-select]').forEach(b=>b.onclick=()=>selectMember(b.dataset.memberSelect))}
async function selectMember(id){try{const d=await apiJson('/auth/select-member',{method:'POST',body:JSON.stringify({memberId:id})});session=d.session;saveSession();$('memberSelectModal').classList.add('hidden');updateShell();await Promise.all([refreshUsers(),refreshRecords()]);showView('verifyView')}catch(e){toast(e.message,4000)}}
$('logoutBtn').onclick=async()=>{try{await apiJson('/auth/logout',{method:'POST'})}catch{}clearSession();showWelcome()};

// ---------- drawer/navigation ----------
$('menuBtn').onclick=openDrawer;$('drawerBackdrop').onclick=closeDrawer;
document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=async()=>{const n=b.dataset.nav;if(n==='verify')showView('verifyView');if(n==='search'){showView('searchView');renderSearch()}if(n==='users'){if(!isAdmin())return;showView('usersView');await refreshUsers()}if(n==='usage'){showView('usageView');await loadUsage()}if(n==='editCompany'){if(!isAdmin())return;showView('editCompanyView');fillCompanyEdit()}if(n==='switchMember'){closeDrawer();await refreshUsers();showMemberSelector()}if(n==='switchCompany'){try{await apiJson('/auth/logout',{method:'POST'})}catch{}clearSession();showView('existingCompanyView');$('menuBtn').classList.add('hidden');$('logoutBtn').classList.add('hidden');$('companySubtitle').textContent='';await loadCompanies()}if(n==='welcome'){try{await apiJson('/auth/logout',{method:'POST'})}catch{}clearSession();showWelcome()}});

// ---------- sticky location ----------
const stickyIds=['city','area','building','floor','room'];
function stickyKey(){return `${STICKY_PREFIX}${session?.company?.id||'none'}`}
function loadSticky(){try{const x=JSON.parse(localStorage.getItem(stickyKey())||'{}');stickyIds.forEach(k=>$(k).value=x[k]||'')}catch{}}
function saveSticky(){const x={};stickyIds.forEach(k=>x[k]=$(k).value.trim());localStorage.setItem(stickyKey(),JSON.stringify(x));return x}
stickyIds.forEach(k=>$(k).addEventListener('change',saveSticky));
function fixedValid(){const x=saveSticky();if(stickyIds.some(k=>!x[k])){toast('Complete City, Area, Building, Floor and Room first.');return false}return true}

// ---------- photos / compression ----------
function blobToDataUrl(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(blob)})}
async function loadImage(file){const url=URL.createObjectURL(file);try{const img=new Image();img.decoding='async';await new Promise((res,rej)=>{img.onload=res;img.onerror=rej;img.src=url});return img}finally{setTimeout(()=>URL.revokeObjectURL(url),1000)}}
function canvasBlob(canvas,q){return new Promise((res,rej)=>canvas.toBlob(b=>b?res(b):rej(new Error('Image compression failed')),'image/jpeg',q))}
async function compressPhoto(file){const img=await loadImage(file);let max=1800;let scale=Math.min(1,max/Math.max(img.naturalWidth,img.naturalHeight));let w=Math.max(1,Math.round(img.naturalWidth*scale)),h=Math.max(1,Math.round(img.naturalHeight*scale));for(let pass=0;pass<4;pass++){const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d',{alpha:false}).drawImage(img,0,0,w,h);for(const q of [.84,.76,.68,.6,.52,.44]){const blob=await canvasBlob(c,q);if(blob.size<=1_000_000)return {blob,dataUrl:await blobToDataUrl(blob),size:blob.size}}w=Math.round(w*.82);h=Math.round(h*.82)}const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d',{alpha:false}).drawImage(img,0,0,w,h);const blob=await canvasBlob(c,.4);return {blob,dataUrl:await blobToDataUrl(blob),size:blob.size}}

function assetDefault(){return {rowId:uid(),assetName:'',quantity:1,serialNumber:'',barcode:'',condition:'Good',verificationStatus:'Found',notFoundReason:''}}
function assetRowHtml(a=assetDefault(),edit=false){const prefix=edit?'e-':'';return `<div class="asset-row" data-row="${escapeHtml(a.rowId||uid())}"><div class="asset-row-grid"><label>Asset Name *<input class="${prefix}asset-name" value="${escapeHtml(a.assetName||'')}"></label><label>Qty *<input class="${prefix}qty" type="number" min="1" value="${Number(a.quantity)||1}"></label><label>Condition<select class="${prefix}condition">${CONDITIONS.map(x=>`<option ${x===a.condition?'selected':''}>${x}</option>`).join('')}</select></label><label>Status<select class="${prefix}status">${STATUSES.map(x=>`<option ${x===a.verificationStatus?'selected':''}>${x}</option>`).join('')}</select></label></div><div class="asset-row-grid secondary-row"><label>Serial Number<input class="${prefix}serial" value="${escapeHtml(a.serialNumber||'')}"></label><label>Barcode / Asset Tag<input class="${prefix}barcode" value="${escapeHtml(a.barcode||'')}"></label><label class="not-found-wrap ${a.verificationStatus==='Not Found'?'':'hidden-field'}">Not Found Reason<select class="${prefix}reason">${NOT_FOUND_REASONS.map(x=>`<option ${x===a.notFoundReason?'selected':''}>${x||'Select reason'}</option>`).join('')}</select></label><button type="button" class="row-remove">Remove</button></div></div>`}
function wireAssetRows(container,edit=false){container.querySelectorAll('.asset-row').forEach(r=>{const p=edit?'e-':'';const st=r.querySelector(`.${p}status`),wrap=r.querySelector('.not-found-wrap');st.onchange=()=>wrap.classList.toggle('hidden-field',st.value!=='Not Found');r.querySelector('.row-remove').onclick=()=>r.remove()})}
function renderAssetRows(list,edit=false){const c=$(edit?'editAssetRows':'assetRows');c.innerHTML=(list?.length?list:[assetDefault()]).map(a=>assetRowHtml(a,edit)).join('');wireAssetRows(c,edit)}
function collectAssetRows(edit=false){const p=edit?'e-':'';return [...$(edit?'editAssetRows':'assetRows').querySelectorAll('.asset-row')].map(r=>({rowId:r.dataset.row||uid(),assetName:r.querySelector(`.${p}asset-name`).value.trim(),quantity:Math.max(1,Number(r.querySelector(`.${p}qty`).value)||1),condition:r.querySelector(`.${p}condition`).value,verificationStatus:r.querySelector(`.${p}status`).value,notFoundReason:r.querySelector(`.${p}reason`).value,serialNumber:r.querySelector(`.${p}serial`).value.trim(),barcode:r.querySelector(`.${p}barcode`).value.trim()}))}

$('takePhotoBtn').onclick=()=>{if(fixedValid())$('cameraInput').click()};$('uploadPhotoBtn').onclick=()=>{if(fixedValid())$('galleryInput').click()};
$('cameraInput').onchange=async e=>{await preparePhoto(e.target.files?.[0],'camera');e.target.value=''};$('galleryInput').onchange=async e=>{await preparePhoto(e.target.files?.[0],'gallery');e.target.value=''};
async function preparePhoto(file,source){if(!file)return;toast('Compressing photo…');try{const c=await compressPhoto(file);const d=new Date();pendingPhoto={dataUrl:c.dataUrl,size:c.size,source,capturedAt:d.toISOString(),photoName:file.name||'photo.jpg'};$('photoPreview').src=c.dataUrl;$('capturedDate').textContent=fmtDate(d);$('capturedTime').textContent=fmtTime(d);const loc=saveSticky();$('locationSnapshot').textContent=`${loc.city} · ${loc.area} · ${loc.building} · Floor ${loc.floor} · Room ${loc.room}`;$('subLocation').value='';$('remarks').value='';fillClickedBy('clickedBy',session.member.id);renderAssetRows([assetDefault()]);$('detailModal').classList.remove('hidden');$('aiStatus').textContent=`Compressed to ${bytesLabel(c.size)}. AI analysing…`;runAi()}catch(e){console.error(e);toast('Could not prepare photo.',4000)}}
async function runAi(){if(!pendingPhoto)return;const seq=++aiSeq;$('retryAiBtn').disabled=true;try{const d=await apiJson('/ai',{method:'POST',body:JSON.stringify({image:pendingPhoto.dataUrl})});if(seq!==aiSeq||!pendingPhoto)return;const list=(d.assets||[]).map(x=>({...assetDefault(),assetName:x.name||'',quantity:x.quantity||1}));if(list.length){renderAssetRows(list);$('aiStatus').textContent=`AI detected ${list.length} asset type${list.length===1?'':'s'}. Verify and edit if required.`}else $('aiStatus').textContent='AI found no clear fixed asset. Add manually.'}catch(e){$('aiStatus').textContent='AI could not identify reliably. Enter assets manually.'}finally{$('retryAiBtn').disabled=false}}
$('retryAiBtn').onclick=runAi;$('addAssetRowBtn').onclick=()=>{$('assetRows').insertAdjacentHTML('beforeend',assetRowHtml(assetDefault()));wireAssetRows($('assetRows'))};$('discardPhotoBtn').onclick=()=>{pendingPhoto=null;aiSeq++;$('detailModal').classList.add('hidden')};
$('savePhotoBtn').onclick=async()=>{if(!pendingPhoto)return;const assets=collectAssetRows();if(!$('subLocation').value.trim()||!$('clickedBy').value||!assets.length||assets.some(a=>!a.assetName)){toast('Complete sub-location, clicked by and all asset names.');return}const loc=saveSticky();try{await apiJson('/records',{method:'POST',body:JSON.stringify({clientId:uid(),photo:pendingPhoto.dataUrl,photoSize:pendingPhoto.size,photoName:pendingPhoto.photoName,capturedAt:pendingPhoto.capturedAt,source:pendingPhoto.source,...loc,subLocation:$('subLocation').value.trim(),clickedByUserId:$('clickedBy').value,remarks:$('remarks').value.trim(),assets})});pendingPhoto=null;$('detailModal').classList.add('hidden');toast('Photo saved to company cloud.');await refreshRecords()}catch(e){toast(e.message,4300)}};

// ---------- records ----------
function flattenAssets(){return records.flatMap(r=>(r.assets||[]).map(a=>({record:r,asset:a})))}
async function refreshRecords(){if(!session)return;try{const d=await apiJson('/records');records=d.records||[];renderRecent();populateFilters()}catch(e){toast(e.message)}}
function renderRecent(){const list=records.slice().sort((a,b)=>new Date(b.capturedAt)-new Date(a.capturedAt));$('photoCount').textContent=list.length;$('assetCount').textContent=flattenAssets().length;$('recordsEmpty').classList.toggle('hidden',list.length>0);$('recordList').innerHTML=list.slice(0,50).map(recordCard).join('');wireRecordActions($('recordList'))}
function statusClass(s){return s==='Found'?'found':s==='Not Found'?'notfound':'pending'}
function recordCard(r){const tags=(r.assets||[]).map(a=>`<span class="asset-tag ${statusClass(a.verificationStatus)}">${escapeHtml(a.assetName)} × ${a.quantity} · ${escapeHtml(a.condition)} · ${escapeHtml(a.verificationStatus)}</span>`).join('');return `<article class="record"><img src="${escapeHtml(r.photoUrl)}" alt="Verification"><div><h3>${escapeHtml(r.building)} · Room ${escapeHtml(r.room)}</h3><p>${escapeHtml(r.city)} · ${escapeHtml(r.area)} · Floor ${escapeHtml(r.floor)} · ${escapeHtml(r.subLocation)}</p><p>${fmtDate(r.capturedAt)} ${fmtTime(r.capturedAt)} · By ${escapeHtml(r.clickedByName||'')}</p>${r.remarks?`<p>Remarks: ${escapeHtml(r.remarks)}</p>`:''}<div class="asset-tags">${tags}</div></div><div class="record-actions"><button class="secondary mini-btn" data-edit-record="${r.id}">Edit</button>${isAdmin()?`<button class="danger mini-btn" data-delete-record="${r.id}">Delete</button>`:''}</div></article>`}
function wireRecordActions(container){container.querySelectorAll('[data-edit-record]').forEach(b=>b.onclick=()=>openRecordEdit(b.dataset.editRecord));container.querySelectorAll('[data-delete-record]').forEach(b=>b.onclick=()=>deleteRecord(b.dataset.deleteRecord))}
async function deleteRecord(id){if(!isAdmin())return;if(!confirm('Delete this photo and its asset rows? Verifiers cannot restore it.'))return;try{await apiJson(`/records/${encodeURIComponent(id)}`,{method:'DELETE'});toast('Deleted');await refreshRecords()}catch(e){toast(e.message)}}
function fillClickedBy(selectId,selected){const s=$(selectId);s.innerHTML=users.filter(u=>u.active!==0).map(u=>`<option value="${u.id}" ${String(u.id)===String(selected)?'selected':''}>${escapeHtml(u.name)}</option>`).join('')}
function openRecordEdit(id){const r=records.find(x=>String(x.id)===String(id));if(!r)return;editingRecord=r;$('editPreview').src=r.photoUrl;$('editRoom').value=r.room;$('editSubLocation').value=r.subLocation;$('editRemarks').value=r.remarks||'';fillClickedBy('editClickedBy',r.clickedByUserId);renderAssetRows(r.assets,true);$('editRecordModal').classList.remove('hidden')}
$('editAddAssetBtn').onclick=()=>{$('editAssetRows').insertAdjacentHTML('beforeend',assetRowHtml(assetDefault(),true));wireAssetRows($('editAssetRows'),true)};
$('saveRecordEditBtn').onclick=async()=>{if(!editingRecord)return;const assets=collectAssetRows(true);if(!$('editRoom').value.trim()||!$('editSubLocation').value.trim()||!$('editClickedBy').value||assets.some(a=>!a.assetName)){toast('Complete required fields.');return}try{await apiJson(`/records/${encodeURIComponent(editingRecord.id)}`,{method:'PUT',body:JSON.stringify({room:$('editRoom').value.trim(),subLocation:$('editSubLocation').value.trim(),clickedByUserId:$('editClickedBy').value,remarks:$('editRemarks').value.trim(),assets})});$('editRecordModal').classList.add('hidden');toast('Changes saved.');await refreshRecords()}catch(e){toast(e.message)}};

// ---------- search/filter ----------
function uniqueVals(key){return [...new Set(records.map(r=>r[key]).filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b)))}
function setOptions(id,vals,label){$(id).innerHTML=`<option value="">All ${label}</option>`+vals.map(v=>`<option>${escapeHtml(v)}</option>`).join('')}
function populateFilters(){setOptions('filterCity',uniqueVals('city'),'Cities');setOptions('filterArea',uniqueVals('area'),'Areas');setOptions('filterBuilding',uniqueVals('building'),'Buildings');setOptions('filterFloor',uniqueVals('floor'),'Floors');setOptions('filterRoom',uniqueVals('room'),'Rooms')}
function renderStatusTabs(){const rows=flattenAssets();const items=[['ALL','All',rows.length],['Found','Found',rows.filter(x=>x.asset.verificationStatus==='Found').length],['Not Found','Not Found',rows.filter(x=>x.asset.verificationStatus==='Not Found').length],['Pending','Pending',rows.filter(x=>x.asset.verificationStatus==='Pending').length],['IMAGES','📷 With Images',records.length]];$('statusTabs').innerHTML=items.map(([k,l,n])=>`<button class="${activeStatus===k?'active':''}" data-status="${k}">${l} (${n})</button>`).join('');$('statusTabs').querySelectorAll('button').forEach(b=>b.onclick=()=>{activeStatus=b.dataset.status;renderSearch()})}
function searchFilteredRecords(){const q=$('searchText').value.trim().toLowerCase(),f={city:$('filterCity').value,area:$('filterArea').value,building:$('filterBuilding').value,floor:$('filterFloor').value,room:$('filterRoom').value,condition:$('filterCondition').value};return records.filter(r=>{if(f.city&&r.city!==f.city)return false;if(f.area&&r.area!==f.area)return false;if(f.building&&r.building!==f.building)return false;if(f.floor&&r.floor!==f.floor)return false;if(f.room&&r.room!==f.room)return false;const assets=r.assets||[];const assetMatch=assets.some(a=>{if(f.condition&&a.condition!==f.condition)return false;if(activeStatus!=='ALL'&&activeStatus!=='IMAGES'&&a.verificationStatus!==activeStatus)return false;const hay=[a.assetName,a.serialNumber,a.barcode,a.condition,a.verificationStatus,a.notFoundReason,r.city,r.area,r.building,r.floor,r.room,r.subLocation,r.remarks,r.clickedByName].join(' ').toLowerCase();return !q||hay.includes(q)});return assetMatch||((activeStatus==='IMAGES'||activeStatus==='ALL')&&!q&&!f.condition)})}
function renderSearch(){renderStatusTabs();const found=searchFilteredRecords();$('searchResults').innerHTML=found.map(recordCard).join('');$('searchEmpty').classList.toggle('hidden',found.length>0);wireRecordActions($('searchResults'))}
['searchText','filterCity','filterArea','filterBuilding','filterFloor','filterRoom','filterCondition'].forEach(id=>$(id).addEventListener(id==='searchText'?'input':'change',renderSearch));
$('clearFiltersBtn').onclick=()=>{['searchText','filterCity','filterArea','filterBuilding','filterFloor','filterRoom','filterCondition'].forEach(id=>$(id).value='');activeStatus='ALL';renderSearch()};

// ---------- users & rights ----------
async function refreshUsers(){if(!session)return;try{const d=await apiJson('/members');users=d.members||[];if(isAdmin())renderUsers()}catch(e){console.error(e)}}
function renderUsers(){$('userCards').innerHTML=users.map(u=>`<article class="user-card"><div class="user-top"><div class="avatar">${escapeHtml((u.name||'?')[0].toUpperCase())}</div><div><h3>${escapeHtml(u.name)}</h3><span class="role-badge ${u.role==='ADMIN'?'admin':''}">${u.role==='ADMIN'?'Admin':'Verifier'}</span></div></div><div class="user-stats"><div><strong>${u.photoCount||0}</strong><small>Photos</small></div><div><strong>${u.assetCount||0}</strong><small>Asset rows</small></div></div><div class="user-actions"><button class="secondary mini-btn" data-user-edit="${u.id}">Edit</button>${String(u.id)!==String(session.member?.id)?`<button class="danger mini-btn" data-user-delete="${u.id}">Delete</button>`:''}</div></article>`).join('');document.querySelectorAll('[data-user-edit]').forEach(b=>b.onclick=()=>openUserModal(b.dataset.userEdit));document.querySelectorAll('[data-user-delete]').forEach(b=>b.onclick=()=>deleteUser(b.dataset.userDelete))}
$('addUserBtn').onclick=()=>openUserModal();
function openUserModal(id=null){editingUser=id?users.find(u=>String(u.id)===String(id)):null;$('userModalTitle').textContent=editingUser?'Edit Team Member':'Add Team Member';$('userName').value=editingUser?.name||'';$('userRole').value=editingUser?.role||'VERIFIER';$('userModal').classList.remove('hidden')}
$('saveUserBtn').onclick=async()=>{const payload={name:$('userName').value.trim(),role:$('userRole').value};if(!payload.name){toast('Team member name is required.');return}try{let result;if(editingUser)result=await apiJson(`/members/${editingUser.id}`,{method:'PUT',body:JSON.stringify(payload)});else result=await apiJson('/members',{method:'POST',body:JSON.stringify(payload)});if(editingUser&&String(editingUser.id)===String(session.member?.id)&&result.session){session=result.session;saveSession();updateShell();if(!isAdmin())showView('verifyView')}$('userModal').classList.add('hidden');toast('Team member saved.');await refreshUsers()}catch(e){toast(e.message,4000)}};
async function deleteUser(id){if(!confirm('Delete this team member from this company? Historical photos keep the saved Clicked By name.'))return;try{await apiJson(`/members/${id}`,{method:'DELETE'});toast('Team member deleted.');await refreshUsers()}catch(e){toast(e.message,4000)}}

// ---------- company settings ----------
function fillCompanyEdit(){$('editCompanyName').value=session.company.name;$('editCompanyStartDate').value=session.company.startDate;$('editCompanyCode').value=session.company.code;$('editCompanyUsername').value=session.company.username||'';$('editCompanyPassword').value=''}
$('saveCompanyBtn').onclick=async()=>{try{const d=await apiJson('/company',{method:'PUT',body:JSON.stringify({name:$('editCompanyName').value.trim(),startDate:$('editCompanyStartDate').value,username:$('editCompanyUsername').value.trim(),newPassword:$('editCompanyPassword').value})});session.company=d.company;saveSession();updateShell();$('editCompanyPassword').value='';toast('Company details updated.')}catch(e){toast(e.message)}};
$('deleteCompanyBtn').onclick=async()=>{if(!isAdmin())return;const name=session.company.name;if(prompt(`Type DELETE ${name} to permanently delete this company`)!==`DELETE ${name}`)return;try{await apiJson('/company',{method:'DELETE'});clearSession();showWelcome();toast('Company deleted.')}catch(e){toast(e.message,4000)}};

// ---------- usage ----------
async function loadUsage(){try{const d=await apiJson('/usage');const pct=Math.min(100,(d.usedBytes/R2_FREE_BYTES)*100);$('usageText').textContent=`${bytesLabel(d.usedBytes)} of 10 GB`;$('usagePercent').textContent=`${pct.toFixed(2)}%`;$('usageBar').style.width=`${pct}%`;$('usagePhotos').textContent=d.photoCount;$('usageAssets').textContent=d.assetCount;$('usageBytes').textContent=bytesLabel(d.usedBytes)}catch(e){toast(e.message)}}

// ---------- Excel export ----------
async function urlToBase64(url){const r=await fetch(url,{headers:authHeaders(false)});if(!r.ok)throw new Error('Photo fetch failed');return await blobToDataUrl(await r.blob())}
$('exportBtn').onclick=async()=>{if(!records.length){toast('No records to export.');return}if(!window.ExcelJS){toast('Excel library is not loaded.');return}toast('Preparing Excel report…',5000);try{const wb=new ExcelJS.Workbook();const ws=wb.addWorksheet('Physical Verification');ws.views=[{state:'frozen',ySplit:1}];ws.columns=[{header:'Sr No',key:'sr',width:8},{header:'Photo',key:'photo',width:24},{header:'Company',key:'company',width:28},{header:'City',key:'city',width:16},{header:'Area',key:'area',width:18},{header:'Building',key:'building',width:22},{header:'Floor',key:'floor',width:12},{header:'Room',key:'room',width:16},{header:'Sub-location',key:'sub',width:22},{header:'Asset Name',key:'asset',width:28},{header:'Quantity',key:'qty',width:10},{header:'Condition',key:'condition',width:16},{header:'Found Status',key:'status',width:15},{header:'Not Found Reason',key:'reason',width:18},{header:'Serial Number',key:'serial',width:20},{header:'Barcode / Asset Tag',key:'barcode',width:20},{header:'Remarks',key:'remarks',width:30},{header:'Clicked By',key:'by',width:20},{header:'Date',key:'date',width:14},{header:'Time',key:'time',width:14}];ws.getRow(1).font={bold:true};ws.getRow(1).height=26;let sr=0,rowNo=2;for(const r of records){let photoId=null;try{const data=await urlToBase64(r.photoUrl);const ext=data.startsWith('data:image/png')?'png':'jpeg';photoId=wb.addImage({base64:data,extension:ext})}catch{}for(const a of r.assets||[]){sr++;const row=ws.addRow({sr,company:session.company.name,city:r.city,area:r.area,building:r.building,floor:r.floor,room:r.room,sub:r.subLocation,asset:a.assetName,qty:a.quantity,condition:a.condition,status:a.verificationStatus,reason:a.notFoundReason||'',serial:a.serialNumber||'',barcode:a.barcode||'',remarks:r.remarks||'',by:r.clickedByName,date:fmtDate(r.capturedAt),time:fmtTime(r.capturedAt)});row.height=84;if(photoId!==null)ws.addImage(photoId,{tl:{col:1,row:rowNo-1},ext:{width:145,height:100}});rowNo++}}const buf=await wb.xlsx.writeBuffer();const blob=new Blob([buf],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${session.company.code}_Physical_Verification_${isoDateInput(new Date())}.xlsx`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000);toast('Excel report generated.')}catch(e){console.error(e);toast('Could not generate Excel report.',4200)}};

// ---------- misc ----------
async function health(){try{await fetch(WORKER_URL)}catch{}}

window.addEventListener('online',()=>{$('syncBadge').textContent='Cloud';refreshRecords()});window.addEventListener('offline',()=>{$('syncBadge').textContent='Offline'});
health();restoreSession();

if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.error));}
