const $ = id => document.getElementById(id);
const WORKER_URL = 'https://pv-capture-ai.mahipal-office21.workers.dev';
const SESSION_KEY = 'prs-assetverify-session-v7';
const STICKY_PREFIX = 'prs-assetverify-sticky-v7-';
const CONDITIONS = ['Good','Fair','Poor','Damaged','Under Repair'];
const STATUSES = ['Found','Not Found','Pending'];
const NOT_FOUND_REASONS = ['','Missing','Disposed','Transferred','Stolen','Under Maintenance'];
const R2_FREE_BYTES = 10 * 1024 * 1024 * 1024;

const PERMISSION_CATALOG = [
  ['verification.view','Verification - View','Open the verification workspace and saved records'],
  ['verification.capture_photo','Verification - Take Photo','Capture a new verification photo'],
  ['verification.upload_gallery','Verification - Gallery Upload','Upload a photo from the device gallery'],
  ['verification.scan','Verification - Scan QR / Barcode','Use Scan & Verify'],
  ['verification.save','Verification - Save','Save a new verification record'],
  ['verification.edit','Verification - Edit','Edit an existing verification record'],
  ['verification.delete','Verification - Delete','Delete a verification record and photo'],
  ['verification.view_images','Verification - View Images','View stored verification photos'],
  ['records.search','Records - Search & Filters','Search and filter verification records'],
  ['records.export','Reports - Export Excel','Export the company verification report to Excel'],
  ['records.view_usage','Reports - Usage','View company photo storage usage'],
  ['members.view','Members - View','View company team members'],
  ['members.create','Members - Add','Add a company team member'],
  ['members.edit','Members - Edit','Edit a team member or assigned role'],
  ['members.delete','Members - Delete','Delete a team member'],
  ['roles.view','Roles - View','View roles and their permissions'],
  ['roles.create','Roles - Create','Create a custom role'],
  ['roles.edit','Roles - Edit','Edit custom role permissions'],
  ['roles.delete','Roles - Delete','Delete an unused custom role'],
  ['roles.assign','Roles - Assign','Assign roles to team members'],
  ['masters.view','Setting & Master - View','View sticky and variable field masters'],
  ['masters.edit','Setting & Master - Edit','Add, edit or delete sticky / variable fields'],
  ['company.edit','Company - Edit','Edit company details and credentials'],
  ['company.delete','Company - Delete','Permanently delete the company workspace']
];

let session = null;
let companies = [];
let records = [];
let users = [];
let roles = [];
let fields = {sticky:[], variable:[]};
let selectedCompany = null;
let pendingRecord = null;
let editingRecord = null;
let editingUser = null;
let editingRole = null;
let editingField = null;
let editingFieldGroup = null;
let aiSeq = 0;
let activeStatus = 'ALL';
let scanner = null;
let scannerRunning = false;

function toast(message, ms=2800){const e=$('toast');e.textContent=message;e.classList.remove('hidden');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.add('hidden'),ms)}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function pad(n){return String(n).padStart(2,'0')}
function fmtDate(d){d=new Date(d);return `${pad(d.getDate())}/${pad(d.getMonth()+1)}/${d.getFullYear()}`}
function fmtTime(d){d=new Date(d);return `${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`}
function isoDateInput(d){const x=new Date(d);return `${x.getFullYear()}-${pad(x.getMonth()+1)}-${pad(x.getDate())}`}
function timeInput(d){const x=new Date(d);return `${pad(x.getHours())}:${pad(x.getMinutes())}:${pad(x.getSeconds())}`}
function combineDateTime(date,time){const d=new Date(`${date}T${time || '00:00:00'}`);return Number.isNaN(d.getTime())?new Date().toISOString():d.toISOString()}
function uid(){return crypto.randomUUID?.() || `${Date.now()}-${Math.random().toString(36).slice(2)}`}
function bytesLabel(n){if(n<1024*1024)return `${(n/1024).toFixed(1)} KB`;if(n<1024*1024*1024)return `${(n/1024/1024).toFixed(1)} MB`;return `${(n/1024/1024/1024).toFixed(2)} GB`}
function hasPermission(code){const p=session?.member?.permissions||[];return p.includes('*')||p.includes(code)}
function authHeaders(body=false){const h={};if(body)h['Content-Type']='application/json';if(session?.token)h.Authorization=`Bearer ${session.token}`;return h}
async function api(path,options={}){const opts={...options,headers:{...authHeaders(!!options.body),...(options.headers||{})}};const r=await fetch(`${WORKER_URL}${path}`,opts);if(r.status===401&&session){clearSession();showWelcome();toast('Company session expired. Please login again.')}return r}
async function apiJson(path,options={}){const r=await api(path,options);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Request failed (${r.status})`);return d}
function saveSession(){localStorage.setItem(SESSION_KEY,JSON.stringify(session))}
function clearSession(){session=null;localStorage.removeItem(SESSION_KEY)}
function loadSession(){try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch{return null}}

const allViews=['welcomeView','createCompanyView','existingCompanyView','verifyView','searchView','usersView','rolesView','mastersView','usageView','editCompanyView'];
function showView(id){allViews.forEach(v=>$(v).classList.toggle('hidden',v!==id));closeDrawer()}
function showWelcome(){showView('welcomeView');$('menuBtn').classList.add('hidden');$('logoutBtn').classList.add('hidden');$('syncBadge').classList.add('hidden');$('companySubtitle').textContent=''}
function openDrawer(){$('drawer').classList.remove('hidden');$('drawerBackdrop').classList.remove('hidden')}
function closeDrawer(){$('drawer').classList.add('hidden');$('drawerBackdrop').classList.add('hidden')}
function updateShell(){if(!session)return;$('menuBtn').classList.remove('hidden');$('logoutBtn').classList.remove('hidden');$('syncBadge').classList.remove('hidden');$('companySubtitle').textContent=session.company.name;$('drawerCompany').textContent=session.company.name;$('drawerUser').textContent=session.member?`${session.member.name} · ${session.member.roleName}`:'Team member not selected';document.querySelectorAll('[data-permission]').forEach(e=>e.classList.toggle('hidden',!hasPermission(e.dataset.permission)));document.querySelectorAll('[data-permission-button]').forEach(e=>{const ok=hasPermission(e.dataset.permissionButton);e.classList.toggle('hidden',!ok);e.disabled=!ok})}

$('menuBtn').onclick=openDrawer;$('drawerBackdrop').onclick=closeDrawer;$('logoutBtn').onclick=async()=>{try{await apiJson('/auth/logout',{method:'POST'})}catch{}clearSession();showWelcome()};

document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=async()=>{const n=b.dataset.nav;if(n==='verify'){showView('verifyView');renderStickyFields();renderRecent()}if(n==='search'){showView('searchView');populateFilters();renderSearch()}if(n==='users'){showView('usersView');await refreshUsers();renderUsers()}if(n==='roles'){showView('rolesView');await refreshRoles();renderRoles()}if(n==='masters'){showView('mastersView');await refreshFields();renderMasters()}if(n==='usage'){showView('usageView');await loadUsage()}if(n==='editCompany'){fillCompanyEdit();showView('editCompanyView')}if(n==='switchMember'){await refreshUsers();showMemberSelector()}if(n==='switchCompany'){clearSession();showView('existingCompanyView');await loadCompanies()}if(n==='welcome'){clearSession();showWelcome()}});

// ---------- Company creation / login ----------
function createMemberRow(data={},locked=false){const wrap=document.createElement('div');wrap.className='member-row member-row-v6';wrap.innerHTML=`<label>Full Name *<input class="cm-name" value="${escapeHtml(data.name||'')}" placeholder="Member name"></label><label>Initial Role *<select class="cm-role"><option value="ADMIN" ${data.role==='ADMIN'?'selected':''}>Admin</option><option value="VERIFIER" ${data.role==='VERIFIER'?'selected':''}>Verifier</option></select></label><button class="remove-member" type="button" ${locked?'disabled':''}>✕</button>`;wrap.querySelector('.remove-member').onclick=()=>wrap.remove();return wrap}
function resetCreateCompany(){$('newCompanyName').value='';$('newCompanyStartDate').value=isoDateInput(new Date());$('newCompanyUsername').value='';$('newCompanyPassword').value='';$('createMembers').innerHTML='';$('createMembers').appendChild(createMemberRow({role:'ADMIN'},true));$('createMembers').appendChild(createMemberRow({role:'VERIFIER'}))}
function collectCreateMembers(){return [...$('createMembers').querySelectorAll('.member-row')].map(r=>({name:r.querySelector('.cm-name').value.trim(),role:r.querySelector('.cm-role').value}))}
$('openCreateCompanyBtn').onclick=()=>{resetCreateCompany();showView('createCompanyView')};$('openExistingCompanyBtn').onclick=async()=>{showView('existingCompanyView');await loadCompanies()};document.querySelectorAll('[data-back-welcome]').forEach(b=>b.onclick=showWelcome);$('addCreateMemberBtn').onclick=()=>$('createMembers').appendChild(createMemberRow({role:'VERIFIER'}));
$('createCompanyBtn').onclick=async()=>{const name=$('newCompanyName').value.trim(),startDate=$('newCompanyStartDate').value,username=$('newCompanyUsername').value.trim(),password=$('newCompanyPassword').value,members=collectCreateMembers();if(!name||!startDate||!username||!password){toast('Complete company name, start date, username and password.');return}if(password.length<6){toast('Company password must be at least 6 characters.');return}if(members.some(m=>!m.name)||!members.some(m=>m.role==='ADMIN')){toast('Every member needs a name and at least one Admin is required.');return}try{const d=await apiJson('/public/companies',{method:'POST',body:JSON.stringify({name,startDate,username,password,members})});session=d.session;saveSession();await enterCompany()}catch(e){toast(e.message,4500)}};

async function loadCompanies(){try{const d=await apiJson('/public/companies');companies=d.companies||[];$('companyList').innerHTML=companies.map(c=>`<div class="company-row"><button data-company="${c.id}"><strong>${escapeHtml(c.name)}</strong><span>${escapeHtml(c.code)}</span></button><span class="company-users">${c.memberCount} member${c.memberCount===1?'':'s'}</span><span class="company-start">Start: ${escapeHtml(c.startDate)}</span><span class="status-active">Active</span></div>`).join('');$('noCompanies').classList.toggle('hidden',companies.length>0);document.querySelectorAll('[data-company]').forEach(b=>b.onclick=()=>openLogin(b.dataset.company))}catch(e){toast(e.message)}}
function openLogin(id){selectedCompany=companies.find(c=>String(c.id)===String(id));if(!selectedCompany)return;$('loginCompanyName').textContent=selectedCompany.name;$('loginUsername').value='';$('loginPassword').value='';$('loginModal').classList.remove('hidden')}
$('loginBtn').onclick=async()=>{try{const d=await apiJson('/auth/login',{method:'POST',body:JSON.stringify({companyId:selectedCompany.id,username:$('loginUsername').value.trim(),password:$('loginPassword').value})});session=d.session;saveSession();$('loginModal').classList.add('hidden');await enterCompany()}catch(e){toast(e.message,4200)}};
$('forgotPasswordBtn').onclick=()=>{$('loginModal').classList.add('hidden');$('forgotStep1').classList.remove('hidden');$('forgotStep2').classList.add('hidden');$('forgotUsername').value=$('loginUsername').value.trim();$('forgotModal').classList.remove('hidden')};
$('sendResetBtn').onclick=async()=>{try{const d=await apiJson('/auth/forgot',{method:'POST',body:JSON.stringify({companyId:selectedCompany.id,username:$('forgotUsername').value.trim()})});$('forgotStep1').classList.add('hidden');$('forgotStep2').classList.remove('hidden');toast(d.emailConfigured?'Reset code sent.':'Reset request created, but email delivery is not configured yet.',4500)}catch(e){toast(e.message,4200)}};
$('resetPasswordBtn').onclick=async()=>{try{await apiJson('/auth/reset',{method:'POST',body:JSON.stringify({companyId:selectedCompany.id,username:$('forgotUsername').value.trim(),code:$('resetCode').value.trim(),newPassword:$('newPassword').value})});$('forgotModal').classList.add('hidden');toast('Company password changed.');openLogin(selectedCompany.id)}catch(e){toast(e.message,4200)}};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).classList.add('hidden'));

async function restoreSession(){session=loadSession();if(!session){showWelcome();return}try{const d=await apiJson('/auth/me');session=d.session;saveSession();await enterCompany()}catch{clearSession();showWelcome()}}
async function enterCompany(){updateShell();await Promise.all([refreshUsers(),refreshRoles(),refreshFields()]);renderStickyFields();if(!session.member){showMemberSelector();return}await refreshRecords();showView('verifyView')}
function showMemberSelector(){$('memberSelectList').innerHTML=users.filter(u=>u.active!==0).map(u=>`<button class="member-select-btn" data-member-select="${u.id}"><span>${escapeHtml(u.name)}</span><small>${escapeHtml(u.roleName||'Role')}</small></button>`).join('');$('memberSelectModal').classList.remove('hidden');document.querySelectorAll('[data-member-select]').forEach(b=>b.onclick=()=>selectMember(b.dataset.memberSelect))}
async function selectMember(id){try{const d=await apiJson('/auth/select-member',{method:'POST',body:JSON.stringify({memberId:id})});session=d.session;saveSession();$('memberSelectModal').classList.add('hidden');updateShell();await Promise.all([refreshUsers(),refreshRoles(),refreshFields(),refreshRecords()]);renderStickyFields();showView('verifyView')}catch(e){toast(e.message)}}

// ---------- Dynamic fields ----------
function fieldDefaultValue(def){if(def.type==='number')return '';return ''}
function stickyKey(){return STICKY_PREFIX + session.company.id}
function loadSticky(){try{return JSON.parse(localStorage.getItem(stickyKey())||'{}')}catch{return {}}}
function saveStickyFromDom(){const out={};fields.sticky.forEach(f=>{const el=$(`sticky_${f.id}`);if(el)out[f.id]=el.value});localStorage.setItem(stickyKey(),JSON.stringify(out));return out}
function fieldInputHtml(def,value='',idPrefix='field'){const id=`${idPrefix}_${def.id}`;const val=escapeHtml(value??'');if(def.type==='textarea')return `<label class="dynamic-field">${escapeHtml(def.label)}<textarea id="${id}" rows="3">${val}</textarea></label>`;if(def.type==='select'){const opts=(def.options||[]).map(o=>`<option ${String(o)===String(value)?'selected':''}>${escapeHtml(o)}</option>`).join('');return `<label class="dynamic-field">${escapeHtml(def.label)}<select id="${id}"><option value=""></option>${opts}</select></label>`}if(def.type==='member'){const opts=users.filter(u=>u.active!==0).map(u=>`<option value="${u.id}" ${String(u.id)===String(value)?'selected':''}>${escapeHtml(u.name)}</option>`).join('');return `<label class="dynamic-field">${escapeHtml(def.label)}<select id="${id}"><option value=""></option>${opts}</select></label>`}return `<label class="dynamic-field">${escapeHtml(def.label)}<input id="${id}" type="${def.type==='number'?'number':'text'}" value="${val}" /></label>`}
function renderStickyFields(){const vals=loadSticky();$('stickyFieldsContainer').innerHTML=fields.sticky.map(f=>fieldInputHtml(f,vals[f.id]??fieldDefaultValue(f),'sticky')).join('')||'<div class="empty">No sticky fields configured.</div>';fields.sticky.forEach(f=>{const el=$(`sticky_${f.id}`);if(el)el.addEventListener('change',saveStickyFromDom)})}
function collectFieldValues(group,prefix){const defs=fields[group];const out={};defs.forEach(f=>{const el=$(`${prefix}_${f.id}`);if(el)out[f.id]=el.value});return out}
function renderVariableFields(containerId,values={},prefix='variable'){$(containerId).innerHTML=fields.variable.map(f=>fieldInputHtml(f,values[f.id]??(f.systemKey==='clickedBy'?session.member?.id:''),prefix)).join('')||'<div class="empty">No variable fields configured.</div>'}
function fieldLabelById(id){return [...fields.sticky,...fields.variable].find(f=>String(f.id)===String(id))?.label||id}

async function refreshFields(){if(!session)return;try{const d=await apiJson('/fields');fields={sticky:d.sticky||[],variable:d.variable||[]};if(!$('mastersView').classList.contains('hidden'))renderMasters()}catch(e){console.error(e)}}
function renderMasters(){const render=(list,group,target)=>{$(target).innerHTML=list.map(f=>`<div class="master-item"><div><strong>${escapeHtml(f.label)}</strong><small>${escapeHtml(f.type)}${f.options?.length?` · ${escapeHtml(f.options.join(', '))}`:''}${f.systemKey?` · default: ${escapeHtml(f.systemKey)}`:''}</small></div><div class="master-actions">${hasPermission('masters.edit')?`<button class="secondary mini-btn" data-field-edit="${f.id}" data-field-group="${group}">Edit</button><button class="danger mini-btn" data-field-delete="${f.id}" data-field-group="${group}">Delete</button>`:''}</div></div>`).join('')||'<div class="empty">No fields configured.</div>'};render(fields.sticky,'sticky','stickyMasterList');render(fields.variable,'variable','variableMasterList');document.querySelectorAll('[data-field-edit]').forEach(b=>b.onclick=()=>openFieldModal(b.dataset.fieldGroup,b.dataset.fieldEdit));document.querySelectorAll('[data-field-delete]').forEach(b=>b.onclick=()=>deleteField(b.dataset.fieldGroup,b.dataset.fieldDelete))}
$('addStickyFieldBtn').onclick=()=>openFieldModal('sticky');$('addVariableFieldBtn').onclick=()=>openFieldModal('variable');$('fieldType').onchange=()=>$('fieldOptionsWrap').classList.toggle('hidden',$('fieldType').value!=='select');
function openFieldModal(group,id=null){editingFieldGroup=group;editingField=id?fields[group].find(f=>String(f.id)===String(id)):null;$('fieldModalTitle').textContent=`${editingField?'Edit':'Add'} ${group==='sticky'?'Sticky':'Variable'} Field`;$('fieldLabel').value=editingField?.label||'';$('fieldType').value=editingField?.type||'text';$('fieldOptions').value=(editingField?.options||[]).join(', ');$('fieldOptionsWrap').classList.toggle('hidden',$('fieldType').value!=='select');$('fieldModal').classList.remove('hidden')}
$('saveFieldBtn').onclick=async()=>{const payload={group:editingFieldGroup,label:$('fieldLabel').value.trim(),type:$('fieldType').value,options:$('fieldType').value==='select'?$('fieldOptions').value.split(',').map(x=>x.trim()).filter(Boolean):[]};if(!payload.label){toast('Field label is required.');return}try{if(editingField)await apiJson(`/fields/${editingField.id}`,{method:'PUT',body:JSON.stringify(payload)});else await apiJson('/fields',{method:'POST',body:JSON.stringify(payload)});$('fieldModal').classList.add('hidden');await refreshFields();renderMasters();renderStickyFields();toast('Field master updated.')}catch(e){toast(e.message,4200)}};
async function deleteField(group,id){const f=fields[group].find(x=>String(x.id)===String(id));if(!confirm(`Delete field "${f?.label||id}"? Existing historical values remain stored but the field will no longer appear.`))return;try{await apiJson(`/fields/${id}`,{method:'DELETE'});await refreshFields();renderMasters();renderStickyFields();toast('Field deleted.')}catch(e){toast(e.message,4200)}}

// ---------- GPS ----------
function getCurrentGps(){return new Promise(resolve=>{if(!navigator.geolocation){resolve({latitude:'',longitude:'',accuracy:'',error:'Geolocation is not supported on this device.'});return}navigator.geolocation.getCurrentPosition(p=>resolve({latitude:p.coords.latitude.toFixed(7),longitude:p.coords.longitude.toFixed(7),accuracy:Math.round(p.coords.accuracy),error:''}),e=>resolve({latitude:'',longitude:'',accuracy:'',error:e.message||'GPS unavailable'}),{enableHighAccuracy:true,timeout:15000,maximumAge:0})})}

// ---------- Image / asset rows ----------
function assetDefault(){return {rowId:uid(),assetName:'',quantity:1,condition:'Good',verificationStatus:'Found',notFoundReason:'',serialNumber:'',barcode:''}}
function statusClass(s){return s==='Found'?'found':s==='Not Found'?'notfound':'pending'}
function assetRowHtml(a={},edit=false){const p=edit?'e-':'';return `<div class="asset-row" data-row="${escapeHtml(a.rowId||uid())}"><div class="grid two"><label>Asset Name *<input class="${p}asset-name" value="${escapeHtml(a.assetName||a.name||'')}"></label><label>Quantity<input class="${p}qty" type="number" min="1" value="${Number(a.quantity)||1}"></label><label>Condition<select class="${p}condition">${CONDITIONS.map(x=>`<option ${x===a.condition?'selected':''}>${x}</option>`).join('')}</select></label><label>Found Status<select class="${p}status">${STATUSES.map(x=>`<option ${x===a.verificationStatus?'selected':''}>${x}</option>`).join('')}</select></label><label class="reason-wrap">Not Found Reason<select class="${p}reason">${NOT_FOUND_REASONS.map(x=>`<option ${x===a.notFoundReason?'selected':''}>${x}</option>`).join('')}</select></label><label>Serial Number<input class="${p}serial" value="${escapeHtml(a.serialNumber||'')}"></label><label>Barcode / QR / Asset Tag<input class="${p}barcode" value="${escapeHtml(a.barcode||'')}"></label></div><button type="button" class="remove-asset danger mini-btn">Remove</button></div>`}
function wireAssetRows(container){container.querySelectorAll('.remove-asset').forEach(b=>b.onclick=()=>b.closest('.asset-row').remove());container.querySelectorAll('select[class$="status"]').forEach(s=>{const sync=()=>{const w=s.closest('.asset-row').querySelector('.reason-wrap');w.classList.toggle('hidden',s.value!=='Not Found')};s.addEventListener('change',sync);sync()})}
function renderAssetRows(list,edit=false){const c=$(edit?'editAssetRows':'assetRows');c.innerHTML=(list?.length?list:[assetDefault()]).map(a=>assetRowHtml(a,edit)).join('');wireAssetRows(c)}
function collectAssetRows(edit=false){const p=edit?'e-':'';return [...$(edit?'editAssetRows':'assetRows').querySelectorAll('.asset-row')].map(r=>({rowId:r.dataset.row||uid(),assetName:r.querySelector(`.${p}asset-name`).value.trim(),quantity:Math.max(1,Number(r.querySelector(`.${p}qty`).value)||1),condition:r.querySelector(`.${p}condition`).value,verificationStatus:r.querySelector(`.${p}status`).value,notFoundReason:r.querySelector(`.${p}reason`).value,serialNumber:r.querySelector(`.${p}serial`).value.trim(),barcode:r.querySelector(`.${p}barcode`).value.trim()})).filter(a=>a.assetName)}
async function fileToDataUrl(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}
async function compressPhoto(file){const src=await fileToDataUrl(file);const img=await new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=reject;i.src=src});let w=img.width,h=img.height;const max=1800;if(Math.max(w,h)>max){const s=max/Math.max(w,h);w=Math.round(w*s);h=Math.round(h*s)}const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d');ctx.drawImage(img,0,0,w,h);let q=.82,blob;do{blob=await new Promise(res=>canvas.toBlob(res,'image/jpeg',q));q-=.08}while(blob&&blob.size>1024*1024&&q>.3);return {dataUrl:await blobToDataUrl(blob),size:blob.size}}
function blobToDataUrl(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(blob)})}

function stickySnapshotText(sticky){return fields.sticky.map(f=>`${f.label}: ${sticky[f.id]||'—'}`).join(' · ')}
function setCaptureDateTime(iso){const d=new Date(iso);$('capturedDateInput').value=isoDateInput(d);$('capturedTimeInput').value=timeInput(d)}

$('takePhotoBtn').onclick=()=>{if(!hasPermission('verification.capture_photo'))return;saveStickyFromDom();$('cameraInput').click()};$('uploadPhotoBtn').onclick=()=>{if(!hasPermission('verification.upload_gallery'))return;saveStickyFromDom();$('galleryInput').click()};
$('cameraInput').onchange=async e=>{await preparePhoto(e.target.files?.[0],'camera');e.target.value=''};$('galleryInput').onchange=async e=>{await preparePhoto(e.target.files?.[0],'gallery');e.target.value=''};
async function preparePhoto(file,source){if(!file)return;toast('Compressing photo and getting GPS…',4500);try{const [c,gps]=await Promise.all([compressPhoto(file),getCurrentGps()]);const d=new Date();pendingRecord={dataUrl:c.dataUrl,size:c.size,source,capturedAt:d.toISOString(),photoName:file.name||'photo.jpg',scanCode:'',gps};$('detailTitle').textContent='Add photo details';$('photoPreview').src=c.dataUrl;$('photoPreview').classList.remove('hidden');$('scanOnlyPreview').classList.add('hidden');$('retryAiBtn').classList.remove('hidden');setCaptureDateTime(d);$('latitude').value=gps.latitude;$('longitude').value=gps.longitude;$('gpsAccuracy').value=gps.accuracy;$('gpsNote').textContent=gps.error?`GPS: ${gps.error}`:`GPS captured with approximately ${gps.accuracy} m device accuracy.`;const sticky=saveStickyFromDom();$('locationSnapshot').textContent=stickySnapshotText(sticky);renderVariableFields('variableFieldsContainer',{},'variable');renderAssetRows([assetDefault()]);$('detailModal').classList.remove('hidden');$('aiStatus').textContent=`Compressed to ${bytesLabel(c.size)}. AI analysing…`;runAi()}catch(e){console.error(e);toast('Could not prepare photo.',4200)}}
async function runAi(){if(!pendingRecord?.dataUrl)return;const seq=++aiSeq;$('retryAiBtn').disabled=true;try{const d=await apiJson('/ai',{method:'POST',body:JSON.stringify({image:pendingRecord.dataUrl})});if(seq!==aiSeq||!pendingRecord)return;const list=(d.assets||[]).map(x=>({...assetDefault(),assetName:x.name||'',quantity:x.quantity||1}));if(list.length){renderAssetRows(list);$('aiStatus').textContent=`AI detected ${list.length} asset type${list.length===1?'':'s'}. Verify and edit if required.`}else $('aiStatus').textContent='AI found no clear fixed asset. Add manually.'}catch{$('aiStatus').textContent='AI could not identify reliably. Enter assets manually.'}finally{$('retryAiBtn').disabled=false}}
$('retryAiBtn').onclick=runAi;$('addAssetRowBtn').onclick=()=>{$('assetRows').insertAdjacentHTML('beforeend',assetRowHtml(assetDefault()));wireAssetRows($('assetRows'))};$('discardPhotoBtn').onclick=()=>{pendingRecord=null;aiSeq++;$('detailModal').classList.add('hidden')};

function clickedByFromVariable(variable){const f=fields.variable.find(x=>x.systemKey==='clickedBy');return f&&variable[f.id]?variable[f.id]:session.member.id}
$('savePhotoBtn').onclick=async()=>{if(!pendingRecord||!hasPermission('verification.save'))return;const assets=collectAssetRows();if(!assets.length){toast('Enter at least one asset name.');return}const sticky=saveStickyFromDom(),variable=collectFieldValues('variable','variable');const capturedAt=combineDateTime($('capturedDateInput').value,$('capturedTimeInput').value);try{await apiJson('/records',{method:'POST',body:JSON.stringify({clientId:uid(),photo:pendingRecord.dataUrl||null,photoSize:pendingRecord.size||0,photoName:pendingRecord.photoName||'',capturedAt,source:pendingRecord.source,scanCode:pendingRecord.scanCode||'',latitude:$('latitude').value.trim(),longitude:$('longitude').value.trim(),gpsAccuracy:$('gpsAccuracy').value.trim(),sticky,variable,clickedByMemberId:clickedByFromVariable(variable),assets})});pendingRecord=null;$('detailModal').classList.add('hidden');toast('Verification saved to company cloud.');await refreshRecords()}catch(e){toast(e.message,4500)}};

// ---------- Scan & Verify ----------
$('scanVerifyBtn').onclick=()=>openScanner();$('closeScannerBtn').onclick=closeScanner;$('startScannerBtn').onclick=startScanner;$('scanImageBtn').onclick=()=>$('scanImageInput').click();$('scanImageInput').onchange=async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;if(!window.Html5Qrcode){toast('Scanner library is unavailable.');return}try{const qr=new Html5Qrcode('qrReader');const code=await qr.scanFile(f,true);$('manualScanCode').value=code;$('scanStatus').textContent='Code detected from image.'}catch(e){$('scanStatus').textContent='No readable barcode / QR found in that image.'}};$('useScanCodeBtn').onclick=async()=>{const code=$('manualScanCode').value.trim();if(!code){toast('Scan or enter a code first.');return}await closeScanner();await prepareScanRecord(code)};
function openScanner(){if(!hasPermission('verification.scan'))return;$('manualScanCode').value='';$('scanStatus').textContent='';$('scannerModal').classList.remove('hidden')}
async function startScanner(){if(scannerRunning)return;if(!window.Html5Qrcode){toast('Scanner library is unavailable.');return}try{scanner=new Html5Qrcode('qrReader');scannerRunning=true;$('scanStatus').textContent='Starting camera…';await scanner.start({facingMode:'environment'},{fps:10,qrbox:{width:250,height:180}},async decoded=>{$('manualScanCode').value=decoded;$('scanStatus').textContent='Code detected.';await stopScanner()},()=>{});$('scanStatus').textContent='Point the camera at a barcode or QR code.'}catch(e){scannerRunning=false;$('scanStatus').textContent=`Camera scanner could not start: ${e}`}}
async function stopScanner(){if(scanner&&scannerRunning){try{await scanner.stop();await scanner.clear()}catch{}scannerRunning=false;scanner=null}}
async function closeScanner(){await stopScanner();$('scannerModal').classList.add('hidden')}
async function prepareScanRecord(code){toast('Getting GPS…',3000);const gps=await getCurrentGps(),d=new Date();pendingRecord={dataUrl:null,size:0,source:'scan',capturedAt:d.toISOString(),photoName:'',scanCode:code,gps};$('detailTitle').textContent='Scan & Verify Details';$('photoPreview').classList.add('hidden');$('scanOnlyPreview').classList.remove('hidden');$('scanOnlyCode').textContent=code;$('retryAiBtn').classList.add('hidden');$('aiStatus').textContent='Barcode / QR value has been placed in the asset row and remains editable.';setCaptureDateTime(d);$('latitude').value=gps.latitude;$('longitude').value=gps.longitude;$('gpsAccuracy').value=gps.accuracy;$('gpsNote').textContent=gps.error?`GPS: ${gps.error}`:`GPS captured with approximately ${gps.accuracy} m device accuracy.`;const sticky=saveStickyFromDom();$('locationSnapshot').textContent=stickySnapshotText(sticky);renderVariableFields('variableFieldsContainer',{},'variable');renderAssetRows([{...assetDefault(),barcode:code}]);$('detailModal').classList.remove('hidden')}

// ---------- Records ----------
async function refreshRecords(){if(!session?.member)return;try{const d=await apiJson('/records');records=d.records||[];renderRecent();populateFilters();if(!$('searchView').classList.contains('hidden'))renderSearch()}catch(e){console.error(e)}}
function flattenAssets(){return records.flatMap(r=>(r.assets||[]).map(a=>({record:r,asset:a})))}
function recordCard(r){const tags=(r.assets||[]).map(a=>`<span class="asset-tag ${statusClass(a.verificationStatus)}">${escapeHtml(a.assetName)} × ${a.quantity} · ${escapeHtml(a.condition)} · ${escapeHtml(a.verificationStatus)}</span>`).join('');const sticky=fields.sticky.map(f=>`${escapeHtml(f.label)}: ${escapeHtml(r.sticky?.[f.id]||'')}`).filter(x=>!x.endsWith(': ')).join(' · ');const gps=r.latitude&&r.longitude?`<span class="gps-chip">GPS ${escapeHtml(r.latitude)}, ${escapeHtml(r.longitude)}</span>`:'';const img=r.photoUrl&&hasPermission('verification.view_images')?`<img src="${escapeHtml(r.photoUrl)}" alt="Verification">`:'';return `<article class="record ${img?'':'no-photo'}">${img}<div class="record-body"><div class="record-source">${escapeHtml(r.source||'record')}</div><h3>${escapeHtml((r.assets?.[0]?.assetName)||r.scanCode||'Verification')}</h3><p>${sticky||'No sticky fields'}</p><p>${fmtDate(r.capturedAt)} ${fmtTime(r.capturedAt)} · By ${escapeHtml(r.clickedByName||'')}</p>${gps}${r.scanCode?`<p>Scanned Code: ${escapeHtml(r.scanCode)}</p>`:''}<div class="asset-tags">${tags}</div></div><div class="record-actions">${hasPermission('verification.edit')?`<button class="secondary mini-btn" data-edit-record="${r.id}">Edit</button>`:''}${hasPermission('verification.delete')?`<button class="danger mini-btn" data-delete-record="${r.id}">Delete</button>`:''}</div></article>`}
function renderRecent(){const list=records.slice().sort((a,b)=>new Date(b.capturedAt)-new Date(a.capturedAt));$('photoCount').textContent=list.length;$('assetCount').textContent=flattenAssets().length;$('recordsEmpty').classList.toggle('hidden',list.length>0);$('recordList').innerHTML=list.slice(0,50).map(recordCard).join('');wireRecordActions($('recordList'))}
function wireRecordActions(container){container.querySelectorAll('[data-edit-record]').forEach(b=>b.onclick=()=>openEditRecord(b.dataset.editRecord));container.querySelectorAll('[data-delete-record]').forEach(b=>b.onclick=()=>deleteRecord(b.dataset.deleteRecord))}
async function deleteRecord(id){if(!confirm('Delete this verification record and its stored photo?'))return;try{await apiJson(`/records/${id}`,{method:'DELETE'});toast('Record deleted.');await refreshRecords()}catch(e){toast(e.message,4200)}}
function renderEditSticky(values){$('editStickyFields').innerHTML=fields.sticky.map(f=>fieldInputHtml(f,values?.[f.id]||'','editSticky')).join('')}
function openEditRecord(id){editingRecord=records.find(r=>String(r.id)===String(id));if(!editingRecord)return;if(editingRecord.photoUrl){$('editPreview').src=editingRecord.photoUrl;$('editPreview').classList.remove('hidden');$('editScanPreview').classList.add('hidden')}else{$('editPreview').classList.add('hidden');$('editScanPreview').classList.remove('hidden');$('editScanPreview').textContent=`Scanned Code: ${editingRecord.scanCode||'—'}`}renderEditSticky(editingRecord.sticky||{});renderVariableFields('editVariableFields',editingRecord.variable||{},'editVariable');const d=new Date(editingRecord.capturedAt);$('editCapturedDate').value=isoDateInput(d);$('editCapturedTime').value=timeInput(d);$('editLatitude').value=editingRecord.latitude||'';$('editLongitude').value=editingRecord.longitude||'';$('editGpsAccuracy').value=editingRecord.gpsAccuracy||'';renderAssetRows(editingRecord.assets||[],true);$('editRecordModal').classList.remove('hidden')}
$('editAddAssetBtn').onclick=()=>{$('editAssetRows').insertAdjacentHTML('beforeend',assetRowHtml(assetDefault(),true));wireAssetRows($('editAssetRows'))};$('saveRecordEditBtn').onclick=async()=>{if(!editingRecord)return;const assets=collectAssetRows(true);if(!assets.length){toast('At least one asset is required.');return}try{const sticky=collectFieldValues('sticky','editSticky'),variable=collectFieldValues('variable','editVariable');const d=await apiJson(`/records/${editingRecord.id}`,{method:'PUT',body:JSON.stringify({capturedAt:combineDateTime($('editCapturedDate').value,$('editCapturedTime').value),latitude:$('editLatitude').value.trim(),longitude:$('editLongitude').value.trim(),gpsAccuracy:$('editGpsAccuracy').value.trim(),sticky,variable,clickedByMemberId:clickedByFromVariable(variable),assets})});$('editRecordModal').classList.add('hidden');toast('Record updated.');await refreshRecords()}catch(e){toast(e.message,4200)}};

// ---------- Search & filters ----------
function uniqueFieldVals(fieldId){return [...new Set(records.map(r=>r.sticky?.[fieldId]).filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b)))}
function populateFilters(){$('dynamicFilters').innerHTML=fields.sticky.map(f=>`<label>${escapeHtml(f.label)}<select data-filter-field="${f.id}"><option value="">All ${escapeHtml(f.label)}</option>${uniqueFieldVals(f.id).map(v=>`<option>${escapeHtml(v)}</option>`).join('')}</select></label>`).join('');$('dynamicFilters').querySelectorAll('select').forEach(s=>s.addEventListener('change',renderSearch))}
function renderStatusTabs(){const rows=flattenAssets();const items=[['ALL','All',rows.length],['Found','Found',rows.filter(x=>x.asset.verificationStatus==='Found').length],['Not Found','Not Found',rows.filter(x=>x.asset.verificationStatus==='Not Found').length],['Pending','Pending',rows.filter(x=>x.asset.verificationStatus==='Pending').length],['IMAGES','📷 With Images',records.filter(r=>r.photoUrl).length]];$('statusTabs').innerHTML=items.map(([k,l,n])=>`<button class="${activeStatus===k?'active':''}" data-status="${k}">${l} (${n})</button>`).join('');$('statusTabs').querySelectorAll('button').forEach(b=>b.onclick=()=>{activeStatus=b.dataset.status;renderSearch()})}
function searchFilteredRecords(){const q=$('searchText').value.trim().toLowerCase(),condition=$('filterCondition').value,filters=[...$('dynamicFilters').querySelectorAll('select')].map(s=>[s.dataset.filterField,s.value]).filter(x=>x[1]);return records.filter(r=>{for(const [id,v] of filters)if(String(r.sticky?.[id]||'')!==v)return false;if(activeStatus==='IMAGES'&&!r.photoUrl)return false;const assets=r.assets||[];const assetMatch=assets.some(a=>{if(condition&&a.condition!==condition)return false;if(activeStatus!=='ALL'&&activeStatus!=='IMAGES'&&a.verificationStatus!==activeStatus)return false;const hay=[a.assetName,a.serialNumber,a.barcode,a.condition,a.verificationStatus,a.notFoundReason,r.scanCode,r.latitude,r.longitude,r.clickedByName,...Object.values(r.sticky||{}),...Object.values(r.variable||{})].join(' ').toLowerCase();return !q||hay.includes(q)});return assetMatch||(!assets.length&&!q)})}
function renderSearch(){renderStatusTabs();const found=searchFilteredRecords();$('searchResults').innerHTML=found.map(recordCard).join('');$('searchEmpty').classList.toggle('hidden',found.length>0);wireRecordActions($('searchResults'))}
$('searchText').addEventListener('input',renderSearch);$('filterCondition').addEventListener('change',renderSearch);$('clearFiltersBtn').onclick=()=>{$('searchText').value='';$('filterCondition').value='';$('dynamicFilters').querySelectorAll('select').forEach(s=>s.value='');activeStatus='ALL';renderSearch()};

// ---------- Roles & permissions ----------
async function refreshRoles(){if(!session)return;try{const d=await apiJson('/roles');roles=d.roles||[];if(!$('rolesView').classList.contains('hidden'))renderRoles();fillRoleSelects()}catch(e){console.error(e)}}
function fillRoleSelects(){const opts=roles.map(r=>`<option value="${r.id}">${escapeHtml(r.name)}</option>`).join('');$('userRole').innerHTML=opts}
function renderRoles(){$('roleCards').innerHTML=roles.map(r=>`<article class="role-card"><h3>${escapeHtml(r.name)}</h3><p>${escapeHtml(r.description||'')}</p><div class="role-meta"><span class="pill">${r.systemRole?'System':'Custom'}</span><span class="pill">${r.memberCount||0} member(s)</span><span class="pill">${r.permissions?.length||0} permission(s)</span></div><div class="role-actions">${hasPermission('roles.edit')&&!r.systemRole?`<button class="secondary mini-btn" data-role-edit="${r.id}">Edit Permissions</button>`:''}${hasPermission('roles.delete')&&!r.systemRole?`<button class="danger mini-btn" data-role-delete="${r.id}">Delete</button>`:''}</div></article>`).join('');document.querySelectorAll('[data-role-edit]').forEach(b=>b.onclick=()=>openRoleModal(b.dataset.roleEdit));document.querySelectorAll('[data-role-delete]').forEach(b=>b.onclick=()=>deleteRole(b.dataset.roleDelete))}
$('createRoleBtn').onclick=()=>openRoleModal();
function openRoleModal(id=null){editingRole=id?roles.find(r=>String(r.id)===String(id)):null;$('roleModalTitle').textContent=editingRole?'Edit Role':'Create Role';$('roleName').value=editingRole?.name||'';$('roleDescription').value=editingRole?.description||'';const current=new Set(editingRole?.permissions||[]);$('permissionChecklist').innerHTML=PERMISSION_CATALOG.map(([code,label,desc])=>`<label class="permission-item"><input type="checkbox" value="${code}" ${current.has(code)?'checked':''}><span><strong>${escapeHtml(label)}</strong><small>${escapeHtml(desc)}</small></span></label>`).join('');const assigned=new Set(users.filter(u=>String(u.roleId)===String(editingRole?.id)).map(u=>String(u.id)));$('roleMemberAssignments').innerHTML=users.map(u=>`<label class="assignment-item"><input type="checkbox" value="${u.id}" ${assigned.has(String(u.id))?'checked':''}>${escapeHtml(u.name)}</label>`).join('');$('roleModal').classList.remove('hidden')}
$('saveRoleBtn').onclick=async()=>{const name=$('roleName').value.trim(),description=$('roleDescription').value.trim(),permissions=[...$('permissionChecklist').querySelectorAll('input:checked')].map(x=>x.value),assignMembers=[...$('roleMemberAssignments').querySelectorAll('input:checked')].map(x=>x.value);if(!name){toast('Role name is required.');return}try{const payload={name,description,permissions,assignMembers};if(editingRole)await apiJson(`/roles/${editingRole.id}`,{method:'PUT',body:JSON.stringify(payload)});else await apiJson('/roles',{method:'POST',body:JSON.stringify(payload)});$('roleModal').classList.add('hidden');await Promise.all([refreshRoles(),refreshUsers()]);renderRoles();toast('Role saved.')}catch(e){toast(e.message,4500)}};
async function deleteRole(id){if(!confirm('Delete this custom role? It must not be assigned to any member.'))return;try{await apiJson(`/roles/${id}`,{method:'DELETE'});await refreshRoles();renderRoles();toast('Role deleted.')}catch(e){toast(e.message,4200)}}

// ---------- Team members ----------
async function refreshUsers(){if(!session)return;try{const d=await apiJson('/members');users=d.members||[];if(!$('usersView').classList.contains('hidden'))renderUsers()}catch(e){console.error(e)}}
function renderUsers(){$('userCards').innerHTML=users.map(u=>`<article class="user-card"><div class="user-top"><div class="avatar">${escapeHtml((u.name||'?')[0].toUpperCase())}</div><div><h3>${escapeHtml(u.name)}</h3><span class="role-badge ${u.roleName==='Admin'?'admin':''}">${escapeHtml(u.roleName||'Role')}</span></div></div><div class="user-stats"><div><strong>${u.photoCount||0}</strong><small>Records</small></div><div><strong>${u.assetCount||0}</strong><small>Asset rows</small></div></div><div class="user-actions">${hasPermission('members.edit')?`<button class="secondary mini-btn" data-user-edit="${u.id}">Edit</button>`:''}${hasPermission('members.delete')&&String(u.id)!==String(session.member?.id)?`<button class="danger mini-btn" data-user-delete="${u.id}">Delete</button>`:''}</div></article>`).join('');document.querySelectorAll('[data-user-edit]').forEach(b=>b.onclick=()=>openUserModal(b.dataset.userEdit));document.querySelectorAll('[data-user-delete]').forEach(b=>b.onclick=()=>deleteUser(b.dataset.userDelete))}
$('addUserBtn').onclick=()=>openUserModal();function openUserModal(id=null){editingUser=id?users.find(u=>String(u.id)===String(id)):null;$('userModalTitle').textContent=editingUser?'Edit Team Member':'Add Team Member';$('userName').value=editingUser?.name||'';fillRoleSelects();if(editingUser)$('userRole').value=editingUser.roleId;$('userModal').classList.remove('hidden')}
$('saveUserBtn').onclick=async()=>{const payload={name:$('userName').value.trim(),roleId:$('userRole').value};if(!payload.name||!payload.roleId){toast('Name and role are required.');return}try{let d;if(editingUser)d=await apiJson(`/members/${editingUser.id}`,{method:'PUT',body:JSON.stringify(payload)});else d=await apiJson('/members',{method:'POST',body:JSON.stringify(payload)});if(d.session){session=d.session;saveSession();updateShell()}$('userModal').classList.add('hidden');await Promise.all([refreshUsers(),refreshRoles()]);renderUsers();toast('Team member saved.')}catch(e){toast(e.message,4200)}};
async function deleteUser(id){if(!confirm('Delete this team member? Historical records retain the saved Clicked By name.'))return;try{await apiJson(`/members/${id}`,{method:'DELETE'});await refreshUsers();renderUsers();toast('Team member deleted.')}catch(e){toast(e.message,4200)}}

// ---------- Company / usage ----------
function fillCompanyEdit(){$('editCompanyName').value=session.company.name;$('editCompanyStartDate').value=session.company.startDate;$('editCompanyCode').value=session.company.code;$('editCompanyUsername').value=session.company.username||'';$('editCompanyPassword').value=''}
$('saveCompanyBtn').onclick=async()=>{try{const d=await apiJson('/company',{method:'PUT',body:JSON.stringify({name:$('editCompanyName').value.trim(),startDate:$('editCompanyStartDate').value,username:$('editCompanyUsername').value.trim(),newPassword:$('editCompanyPassword').value})});session.company=d.company;saveSession();updateShell();toast('Company details updated.')}catch(e){toast(e.message,4200)}};
$('deleteCompanyBtn').onclick=async()=>{const name=session.company.name;if(prompt(`Type DELETE ${name} to permanently delete this company`)!==`DELETE ${name}`)return;try{await apiJson('/company',{method:'DELETE'});clearSession();showWelcome();toast('Company deleted.')}catch(e){toast(e.message,4200)}};
async function loadUsage(){try{const d=await apiJson('/usage');const pct=Math.min(100,(d.usedBytes/R2_FREE_BYTES)*100);$('usageText').textContent=`${bytesLabel(d.usedBytes)} of 10 GB`;$('usagePercent').textContent=`${pct.toFixed(2)}%`;$('usageBar').style.width=`${pct}%`;$('usagePhotos').textContent=d.photoCount;$('usageAssets').textContent=d.assetCount;$('usageBytes').textContent=bytesLabel(d.usedBytes)}catch(e){toast(e.message)}}

// ---------- Excel export ----------
async function urlToBase64(url){const r=await fetch(url,{headers:authHeaders(false)});if(!r.ok)throw new Error('Photo fetch failed');return await blobToDataUrl(await r.blob())}
$('exportBtn').onclick=async()=>{if(!hasPermission('records.export'))return;if(!records.length){toast('No records to export.');return}if(!window.ExcelJS){toast('Excel library is not loaded.');return}toast('Preparing Excel report…',5000);try{const wb=new ExcelJS.Workbook(),ws=wb.addWorksheet('Physical Verification');const dynamicSticky=fields.sticky.map((f,i)=>({header:f.label,key:`s_${i}`,width:20,field:f}));const dynamicVariable=fields.variable.map((f,i)=>({header:f.label,key:`v_${i}`,width:20,field:f}));ws.columns=[{header:'Sr No',key:'sr',width:8},{header:'Photo',key:'photo',width:24},{header:'Company',key:'company',width:28},...dynamicSticky,...dynamicVariable,{header:'Latitude',key:'lat',width:16},{header:'Longitude',key:'lon',width:16},{header:'GPS Accuracy (m)',key:'acc',width:16},{header:'Source',key:'source',width:12},{header:'Scanned Code',key:'scan',width:25},{header:'Asset Name',key:'asset',width:28},{header:'Quantity',key:'qty',width:10},{header:'Condition',key:'condition',width:16},{header:'Found Status',key:'status',width:15},{header:'Not Found Reason',key:'reason',width:18},{header:'Serial Number',key:'serial',width:20},{header:'Barcode / QR / Asset Tag',key:'barcode',width:24},{header:'Clicked By',key:'by',width:20},{header:'Date',key:'date',width:14},{header:'Time',key:'time',width:14}];ws.views=[{state:'frozen',ySplit:1}];ws.getRow(1).font={bold:true};let sr=0,rowNo=2;for(const r of records){let photoId=null;if(r.photoUrl){try{const data=await urlToBase64(r.photoUrl),ext=data.startsWith('data:image/png')?'png':'jpeg';photoId=wb.addImage({base64:data,extension:ext})}catch{}}for(const a of r.assets||[]){sr++;const obj={sr,company:session.company.name,lat:r.latitude||'',lon:r.longitude||'',acc:r.gpsAccuracy||'',source:r.source||'',scan:r.scanCode||'',asset:a.assetName,qty:a.quantity,condition:a.condition,status:a.verificationStatus,reason:a.notFoundReason||'',serial:a.serialNumber||'',barcode:a.barcode||'',by:r.clickedByName||'',date:fmtDate(r.capturedAt),time:fmtTime(r.capturedAt)};dynamicSticky.forEach((x,i)=>obj[`s_${i}`]=r.sticky?.[x.field.id]||'');dynamicVariable.forEach((x,i)=>{let v=r.variable?.[x.field.id]||'';if(x.field.type==='member'&&v)v=users.find(u=>String(u.id)===String(v))?.name||v;obj[`v_${i}`]=v});const row=ws.addRow(obj);row.height=84;if(photoId!==null)ws.addImage(photoId,{tl:{col:1,row:rowNo-1},ext:{width:145,height:100}});rowNo++}}const buf=await wb.xlsx.writeBuffer(),blob=new Blob([buf],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${session.company.code}_Physical_Verification_${isoDateInput(new Date())}.xlsx`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000);toast('Excel report generated.')}catch(e){console.error(e);toast('Could not generate Excel report.',4200)}};

async function health(){try{await fetch(WORKER_URL)}catch{}}
window.addEventListener('online',()=>{$('syncBadge').textContent='Cloud';refreshRecords()});window.addEventListener('offline',()=>{$('syncBadge').textContent='Offline'});health();restoreSession();if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.error));
